# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wndMain.ui'
#
# Created: Thu Sep 14 09:41:28 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1082, 679)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setStyleSheet("background-color: rgb(147, 147, 147);")
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_8 = QtGui.QGridLayout(self.frame)
        self.gridLayout_8.setContentsMargins(10, 9, -1, -1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_9 = QtGui.QLabel(self.frame)
        self.label_9.setStyleSheet("font: bold 20pt \"Ubuntu\";\n"
"color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_8.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setContentsMargins(6, 6, 6, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gbConfiguration = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gbConfiguration.sizePolicy().hasHeightForWidth())
        self.gbConfiguration.setSizePolicy(sizePolicy)
        self.gbConfiguration.setStyleSheet("QGroupBox#gbConfiguration{\n"
" border-width: 1px;\n"
" border-style: dotted;\n"
"border-color: gray;\n"
"font: bold 12pt \"Ubuntu\";\n"
" }\n"
"QGroupBox::title#gbConfiguration {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFOECE, stop: 1 #FFFFFF);\n"
"}")
        self.gbConfiguration.setObjectName("gbConfiguration")
        self.gridLayout_2 = QtGui.QGridLayout(self.gbConfiguration)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gbGraylog = QtGui.QGroupBox(self.gbConfiguration)
        self.gbGraylog.setEnabled(True)
        self.gbGraylog.setObjectName("gbGraylog")
        self.gridLayout_3 = QtGui.QGridLayout(self.gbGraylog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.leGraylogIP = QtGui.QLineEdit(self.gbGraylog)
        self.leGraylogIP.setInputMask("")
        self.leGraylogIP.setObjectName("leGraylogIP")
        self.gridLayout_3.addWidget(self.leGraylogIP, 0, 2, 1, 1)
        self.label = QtGui.QLabel(self.gbGraylog)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gbGraylog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 2)
        self.leGraylogPort = QtGui.QLineEdit(self.gbGraylog)
        self.leGraylogPort.setInputMask("")
        self.leGraylogPort.setObjectName("leGraylogPort")
        self.gridLayout_3.addWidget(self.leGraylogPort, 1, 2, 1, 1)
        self.leGraylogHttpPort = QtGui.QLineEdit(self.gbGraylog)
        self.leGraylogHttpPort.setObjectName("leGraylogHttpPort")
        self.gridLayout_3.addWidget(self.leGraylogHttpPort, 2, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gbGraylog)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 1)
        self.pbConnect = QtGui.QPushButton(self.gbGraylog)
        self.pbConnect.setObjectName("pbConnect")
        self.gridLayout_3.addWidget(self.pbConnect, 3, 2, 1, 1)
        self.gridLayout_2.addWidget(self.gbGraylog, 0, 1, 1, 1)
        self.gbAsterix = QtGui.QGroupBox(self.gbConfiguration)
        self.gbAsterix.setObjectName("gbAsterix")
        self.gridLayout = QtGui.QGridLayout(self.gbAsterix)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(self.gbAsterix)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 3)
        self.label_3 = QtGui.QLabel(self.gbAsterix)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.leAsterixSic = QtGui.QLineEdit(self.gbAsterix)
        self.leAsterixSic.setObjectName("leAsterixSic")
        self.gridLayout.addWidget(self.leAsterixSic, 2, 3, 1, 1)
        self.leAsterixPort = QtGui.QLineEdit(self.gbAsterix)
        self.leAsterixPort.setObjectName("leAsterixPort")
        self.gridLayout.addWidget(self.leAsterixPort, 1, 3, 1, 1)
        self.leAsterixIP = QtGui.QLineEdit(self.gbAsterix)
        self.leAsterixIP.setObjectName("leAsterixIP")
        self.gridLayout.addWidget(self.leAsterixIP, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.gbAsterix)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.gbAsterix, 0, 2, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbSaveConfiguration = QtGui.QPushButton(self.gbConfiguration)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbSaveConfiguration.sizePolicy().hasHeightForWidth())
        self.pbSaveConfiguration.setSizePolicy(sizePolicy)
        self.pbSaveConfiguration.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pbSaveConfiguration.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pbSaveConfiguration.setObjectName("pbSaveConfiguration")
        self.verticalLayout.addWidget(self.pbSaveConfiguration)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 3, 1, 2)
        self.gbIamod = QtGui.QGroupBox(self.gbConfiguration)
        self.gbIamod.setObjectName("gbIamod")
        self.gridLayout_4 = QtGui.QGridLayout(self.gbIamod)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtGui.QLabel(self.gbIamod)
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 2)
        self.label_6 = QtGui.QLabel(self.gbIamod)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.leIamodTransponder = QtGui.QLineEdit(self.gbIamod)
        self.leIamodTransponder.setObjectName("leIamodTransponder")
        self.gridLayout_4.addWidget(self.leIamodTransponder, 2, 2, 1, 2)
        self.label_7 = QtGui.QLabel(self.gbIamod)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 2)
        self.leIamodPort = QtGui.QLineEdit(self.gbIamod)
        self.leIamodPort.setObjectName("leIamodPort")
        self.gridLayout_4.addWidget(self.leIamodPort, 0, 2, 1, 2)
        self.leIamodThreshold = QtGui.QLineEdit(self.gbIamod)
        self.leIamodThreshold.setObjectName("leIamodThreshold")
        self.gridLayout_4.addWidget(self.leIamodThreshold, 1, 2, 1, 2)
        self.gridLayout_2.addWidget(self.gbIamod, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.gbConfiguration, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("QGroupBox#groupBox{\n"
" border-width: 1px;\n"
" border-style: dotted;\n"
"border-color: gray;\n"
"font: bold 12pt \"Ubuntu\";\n"
" }\n"
"QGroupBox::title#groupBox {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 0 3px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #FFOECE, stop: 1 #FFFFFF);\n"
"}")
        self.groupBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pbStop = QtGui.QPushButton(self.groupBox)
        self.pbStop.setObjectName("pbStop")
        self.gridLayout_6.addWidget(self.pbStop, 1, 0, 1, 1)
        self.pbStart = QtGui.QPushButton(self.groupBox)
        self.pbStart.setObjectName("pbStart")
        self.gridLayout_6.addWidget(self.pbStart, 0, 0, 1, 1)
        self.statusImage = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusImage.sizePolicy().hasHeightForWidth())
        self.statusImage.setSizePolicy(sizePolicy)
        self.statusImage.setMaximumSize(QtCore.QSize(300, 300))
        self.statusImage.setFrameShadow(QtGui.QFrame.Plain)
        self.statusImage.setText("")
        self.statusImage.setMargin(10)
        self.statusImage.setIndent(0)
        self.statusImage.setObjectName("statusImage")
        self.gridLayout_6.addWidget(self.statusImage, 0, 1, 2, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        self.gridLayout_6.addItem(spacerItem, 2, 0, 1, 2)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 2, 1, 1)
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtGui.QGridLayout(self.widget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.webLayout = QtGui.QGridLayout()
        self.webLayout.setObjectName("webLayout")
        self.gridLayout_7.addLayout(self.webLayout, 0, 0, 1, 2)
        self.gridLayout_5.addWidget(self.widget, 1, 0, 1, 3)
        self.gridLayout_9.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1082, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionLicense = QtGui.QAction(MainWindow)
        self.actionLicense.setObjectName("actionLicense")
        self.actionLoad_Config_File = QtGui.QAction(MainWindow)
        self.actionLoad_Config_File.setObjectName("actionLoad_Config_File")
        self.menuFile.addAction(self.actionLoad_Config_File)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionLicense)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "IAMOD Server Configuration GUI", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "IAMOD Server Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.gbConfiguration.setTitle(QtGui.QApplication.translate("MainWindow", "Configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.gbGraylog.setTitle(QtGui.QApplication.translate("MainWindow", "Graylog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Http Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.gbAsterix.setTitle(QtGui.QApplication.translate("MainWindow", "Asterix Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "IP:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "SIC:", None, QtGui.QApplication.UnicodeUTF8))
        self.pbSaveConfiguration.setText(QtGui.QApplication.translate("MainWindow", "Save\n"
"Configuration\n"
"File", None, QtGui.QApplication.UnicodeUTF8))
        self.gbIamod.setTitle(QtGui.QApplication.translate("MainWindow", "IAMOD", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Transponder Code:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Server", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStop.setText(QtGui.QApplication.translate("MainWindow", "Stop Server", None, QtGui.QApplication.UnicodeUTF8))
        self.pbStart.setText(QtGui.QApplication.translate("MainWindow", "Start Server", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLicense.setText(QtGui.QApplication.translate("MainWindow", "License", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Config_File.setText(QtGui.QApplication.translate("MainWindow", "Load Config File", None, QtGui.QApplication.UnicodeUTF8))

